apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-sm
  namespace: default
  labels:
    serviceMonitorSelector: prometheus
spec:
 endpoints:
   - port: scaleble-service-port # Имя порта из вашего Service.
 namespaceSelector:
   matchNames:
     - default
 selector:
   matchLabels:
    prometheus-monitored: {{ .Chart.Name }}  # Этот тег должен совпадать с тегом в вашем Service.      